# Generated by Django 5.2.17 on 2026-10-02 18:00

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ProjectPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("summary", models.CharField(blank=True, max_length=300)),
                (
                    "technologies",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated, e.g. 'Django, AWS, React'.",
                        max_length=255,
                    ),
                ),
                ("project_url", models.URLField(blank=True)),
                ("repository_url", models.URLField(blank=True)),
                ("completed_on", models.DateField(blank=True, null=True)),
                ("featured", models.BooleanField(default=False)),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 0),
                            ("paragraph", 1),
                            ("image", 4),
                            ("quote", 6),
                            ("embed", 7),
                            ("call_to_action", 11),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "form_classname": "title",
                                    "icon": "title",
                                    "template": "blocks/heading_block.html",
                                },
                            ),
                            1: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"icon": "pilcrow"},
                            ),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 2), ("caption", 3)]],
                                {},
                            ),
                            5: ("wagtail.blocks.TextBlock", (), {}),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 5), ("attribution", 3)]],
                                {},
                            ),
                            7: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {
                                    "help_text": "YouTube, Vimeo, SlideShare, etc.",
                                    "icon": "media",
                                },
                            ),
                            8: ("wagtail.blocks.CharBlock", (), {}),
                            9: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            10: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "Used when no page is selected.",
                                    "required": False,
                                },
                            ),
                            11: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 8), ("page", 9), ("url", 10)]],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
